name: "Template-CI"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: "0 8 * * *"

jobs:
  check-format:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup Project
        run: |
          npm run setup
      - name: templates check
        run: |
          npm run generate:all
        working-directory: ./src
      - name: Check if there are changes
        id: changes
        run: |
          git add .
          VAR=$(git diff --cached --name-only)
          if [ ! -z "$VAR" ]
          then
            echo $VAR
            echo '======================================= Prompt Information ==============================================='
            echo 'There may be some unformatted files in your PR, please run these commands on Git Bash terminal: '
            echo '1. npm run generate:all'
            echo 'please replace the ${your-PR-target-branch} as the target branch of your PR, such as origin/dev or upstream/dev'
            exit 1
          fi